/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mecare.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Audit log event for tracking user actions */
@org.apache.avro.specific.AvroGenerated
public class AuditLog extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3291268009209012338L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AuditLog\",\"namespace\":\"com.mecare.avro\",\"doc\":\"Audit log event for tracking user actions\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"doc\":\"UUID of the audit log entry\",\"default\":null},{\"name\":\"actorId\",\"type\":\"string\",\"doc\":\"UUID of the user/system performing the action\"},{\"name\":\"actorType\",\"type\":\"string\",\"doc\":\"Type of actor (USER, SYSTEM, SERVICE, etc.)\"},{\"name\":\"targetId\",\"type\":[\"null\",\"string\"],\"doc\":\"UUID of the target entity being acted upon\",\"default\":null},{\"name\":\"targetType\",\"type\":\"string\",\"doc\":\"Type of target entity\"},{\"name\":\"actionTypeCode\",\"type\":\"string\",\"doc\":\"Code referencing audit_action_types table\"},{\"name\":\"actionCategoryCode\",\"type\":\"string\",\"doc\":\"Code referencing audit_action_categories table\"},{\"name\":\"impersonatedUserId\",\"type\":[\"null\",\"string\"],\"doc\":\"UUID if action performed on behalf of another user\",\"default\":null},{\"name\":\"previousData\",\"type\":[\"null\",\"string\"],\"doc\":\"JSON string of previous state\",\"default\":null},{\"name\":\"newData\",\"type\":[\"null\",\"string\"],\"doc\":\"JSON string of new state\",\"default\":null},{\"name\":\"ipAddress\",\"type\":[\"null\",\"string\"],\"doc\":\"Client IP address\",\"default\":null},{\"name\":\"userAgent\",\"type\":[\"null\",\"string\"],\"doc\":\"Client user agent string\",\"default\":null},{\"name\":\"sourceDevice\",\"type\":[\"null\",\"string\"],\"doc\":\"Source device identifier\",\"default\":null},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Timestamp when the audit log was created\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<AuditLog> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AuditLog> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AuditLog> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AuditLog> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AuditLog> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AuditLog to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AuditLog from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AuditLog instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AuditLog fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** UUID of the audit log entry */
  private java.lang.CharSequence id;
  /** UUID of the user/system performing the action */
  private java.lang.CharSequence actorId;
  /** Type of actor (USER, SYSTEM, SERVICE, etc.) */
  private java.lang.CharSequence actorType;
  /** UUID of the target entity being acted upon */
  private java.lang.CharSequence targetId;
  /** Type of target entity */
  private java.lang.CharSequence targetType;
  /** Code referencing audit_action_types table */
  private java.lang.CharSequence actionTypeCode;
  /** Code referencing audit_action_categories table */
  private java.lang.CharSequence actionCategoryCode;
  /** UUID if action performed on behalf of another user */
  private java.lang.CharSequence impersonatedUserId;
  /** JSON string of previous state */
  private java.lang.CharSequence previousData;
  /** JSON string of new state */
  private java.lang.CharSequence newData;
  /** Client IP address */
  private java.lang.CharSequence ipAddress;
  /** Client user agent string */
  private java.lang.CharSequence userAgent;
  /** Source device identifier */
  private java.lang.CharSequence sourceDevice;
  /** Timestamp when the audit log was created */
  private java.time.Instant createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AuditLog() {}

  /**
   * All-args constructor.
   * @param id UUID of the audit log entry
   * @param actorId UUID of the user/system performing the action
   * @param actorType Type of actor (USER, SYSTEM, SERVICE, etc.)
   * @param targetId UUID of the target entity being acted upon
   * @param targetType Type of target entity
   * @param actionTypeCode Code referencing audit_action_types table
   * @param actionCategoryCode Code referencing audit_action_categories table
   * @param impersonatedUserId UUID if action performed on behalf of another user
   * @param previousData JSON string of previous state
   * @param newData JSON string of new state
   * @param ipAddress Client IP address
   * @param userAgent Client user agent string
   * @param sourceDevice Source device identifier
   * @param createdAt Timestamp when the audit log was created
   */
  public AuditLog(java.lang.CharSequence id, java.lang.CharSequence actorId, java.lang.CharSequence actorType, java.lang.CharSequence targetId, java.lang.CharSequence targetType, java.lang.CharSequence actionTypeCode, java.lang.CharSequence actionCategoryCode, java.lang.CharSequence impersonatedUserId, java.lang.CharSequence previousData, java.lang.CharSequence newData, java.lang.CharSequence ipAddress, java.lang.CharSequence userAgent, java.lang.CharSequence sourceDevice, java.time.Instant createdAt) {
    this.id = id;
    this.actorId = actorId;
    this.actorType = actorType;
    this.targetId = targetId;
    this.targetType = targetType;
    this.actionTypeCode = actionTypeCode;
    this.actionCategoryCode = actionCategoryCode;
    this.impersonatedUserId = impersonatedUserId;
    this.previousData = previousData;
    this.newData = newData;
    this.ipAddress = ipAddress;
    this.userAgent = userAgent;
    this.sourceDevice = sourceDevice;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return actorId;
    case 2: return actorType;
    case 3: return targetId;
    case 4: return targetType;
    case 5: return actionTypeCode;
    case 6: return actionCategoryCode;
    case 7: return impersonatedUserId;
    case 8: return previousData;
    case 9: return newData;
    case 10: return ipAddress;
    case 11: return userAgent;
    case 12: return sourceDevice;
    case 13: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: actorId = (java.lang.CharSequence)value$; break;
    case 2: actorType = (java.lang.CharSequence)value$; break;
    case 3: targetId = (java.lang.CharSequence)value$; break;
    case 4: targetType = (java.lang.CharSequence)value$; break;
    case 5: actionTypeCode = (java.lang.CharSequence)value$; break;
    case 6: actionCategoryCode = (java.lang.CharSequence)value$; break;
    case 7: impersonatedUserId = (java.lang.CharSequence)value$; break;
    case 8: previousData = (java.lang.CharSequence)value$; break;
    case 9: newData = (java.lang.CharSequence)value$; break;
    case 10: ipAddress = (java.lang.CharSequence)value$; break;
    case 11: userAgent = (java.lang.CharSequence)value$; break;
    case 12: sourceDevice = (java.lang.CharSequence)value$; break;
    case 13: createdAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return UUID of the audit log entry
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * UUID of the audit log entry
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'actorId' field.
   * @return UUID of the user/system performing the action
   */
  public java.lang.CharSequence getActorId() {
    return actorId;
  }


  /**
   * Sets the value of the 'actorId' field.
   * UUID of the user/system performing the action
   * @param value the value to set.
   */
  public void setActorId(java.lang.CharSequence value) {
    this.actorId = value;
  }

  /**
   * Gets the value of the 'actorType' field.
   * @return Type of actor (USER, SYSTEM, SERVICE, etc.)
   */
  public java.lang.CharSequence getActorType() {
    return actorType;
  }


  /**
   * Sets the value of the 'actorType' field.
   * Type of actor (USER, SYSTEM, SERVICE, etc.)
   * @param value the value to set.
   */
  public void setActorType(java.lang.CharSequence value) {
    this.actorType = value;
  }

  /**
   * Gets the value of the 'targetId' field.
   * @return UUID of the target entity being acted upon
   */
  public java.lang.CharSequence getTargetId() {
    return targetId;
  }


  /**
   * Sets the value of the 'targetId' field.
   * UUID of the target entity being acted upon
   * @param value the value to set.
   */
  public void setTargetId(java.lang.CharSequence value) {
    this.targetId = value;
  }

  /**
   * Gets the value of the 'targetType' field.
   * @return Type of target entity
   */
  public java.lang.CharSequence getTargetType() {
    return targetType;
  }


  /**
   * Sets the value of the 'targetType' field.
   * Type of target entity
   * @param value the value to set.
   */
  public void setTargetType(java.lang.CharSequence value) {
    this.targetType = value;
  }

  /**
   * Gets the value of the 'actionTypeCode' field.
   * @return Code referencing audit_action_types table
   */
  public java.lang.CharSequence getActionTypeCode() {
    return actionTypeCode;
  }


  /**
   * Sets the value of the 'actionTypeCode' field.
   * Code referencing audit_action_types table
   * @param value the value to set.
   */
  public void setActionTypeCode(java.lang.CharSequence value) {
    this.actionTypeCode = value;
  }

  /**
   * Gets the value of the 'actionCategoryCode' field.
   * @return Code referencing audit_action_categories table
   */
  public java.lang.CharSequence getActionCategoryCode() {
    return actionCategoryCode;
  }


  /**
   * Sets the value of the 'actionCategoryCode' field.
   * Code referencing audit_action_categories table
   * @param value the value to set.
   */
  public void setActionCategoryCode(java.lang.CharSequence value) {
    this.actionCategoryCode = value;
  }

  /**
   * Gets the value of the 'impersonatedUserId' field.
   * @return UUID if action performed on behalf of another user
   */
  public java.lang.CharSequence getImpersonatedUserId() {
    return impersonatedUserId;
  }


  /**
   * Sets the value of the 'impersonatedUserId' field.
   * UUID if action performed on behalf of another user
   * @param value the value to set.
   */
  public void setImpersonatedUserId(java.lang.CharSequence value) {
    this.impersonatedUserId = value;
  }

  /**
   * Gets the value of the 'previousData' field.
   * @return JSON string of previous state
   */
  public java.lang.CharSequence getPreviousData() {
    return previousData;
  }


  /**
   * Sets the value of the 'previousData' field.
   * JSON string of previous state
   * @param value the value to set.
   */
  public void setPreviousData(java.lang.CharSequence value) {
    this.previousData = value;
  }

  /**
   * Gets the value of the 'newData' field.
   * @return JSON string of new state
   */
  public java.lang.CharSequence getNewData() {
    return newData;
  }


  /**
   * Sets the value of the 'newData' field.
   * JSON string of new state
   * @param value the value to set.
   */
  public void setNewData(java.lang.CharSequence value) {
    this.newData = value;
  }

  /**
   * Gets the value of the 'ipAddress' field.
   * @return Client IP address
   */
  public java.lang.CharSequence getIpAddress() {
    return ipAddress;
  }


  /**
   * Sets the value of the 'ipAddress' field.
   * Client IP address
   * @param value the value to set.
   */
  public void setIpAddress(java.lang.CharSequence value) {
    this.ipAddress = value;
  }

  /**
   * Gets the value of the 'userAgent' field.
   * @return Client user agent string
   */
  public java.lang.CharSequence getUserAgent() {
    return userAgent;
  }


  /**
   * Sets the value of the 'userAgent' field.
   * Client user agent string
   * @param value the value to set.
   */
  public void setUserAgent(java.lang.CharSequence value) {
    this.userAgent = value;
  }

  /**
   * Gets the value of the 'sourceDevice' field.
   * @return Source device identifier
   */
  public java.lang.CharSequence getSourceDevice() {
    return sourceDevice;
  }


  /**
   * Sets the value of the 'sourceDevice' field.
   * Source device identifier
   * @param value the value to set.
   */
  public void setSourceDevice(java.lang.CharSequence value) {
    this.sourceDevice = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return Timestamp when the audit log was created
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * Timestamp when the audit log was created
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new AuditLog RecordBuilder.
   * @return A new AuditLog RecordBuilder
   */
  public static com.mecare.avro.AuditLog.Builder newBuilder() {
    return new com.mecare.avro.AuditLog.Builder();
  }

  /**
   * Creates a new AuditLog RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AuditLog RecordBuilder
   */
  public static com.mecare.avro.AuditLog.Builder newBuilder(com.mecare.avro.AuditLog.Builder other) {
    if (other == null) {
      return new com.mecare.avro.AuditLog.Builder();
    } else {
      return new com.mecare.avro.AuditLog.Builder(other);
    }
  }

  /**
   * Creates a new AuditLog RecordBuilder by copying an existing AuditLog instance.
   * @param other The existing instance to copy.
   * @return A new AuditLog RecordBuilder
   */
  public static com.mecare.avro.AuditLog.Builder newBuilder(com.mecare.avro.AuditLog other) {
    if (other == null) {
      return new com.mecare.avro.AuditLog.Builder();
    } else {
      return new com.mecare.avro.AuditLog.Builder(other);
    }
  }

  /**
   * RecordBuilder for AuditLog instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AuditLog>
    implements org.apache.avro.data.RecordBuilder<AuditLog> {

    /** UUID of the audit log entry */
    private java.lang.CharSequence id;
    /** UUID of the user/system performing the action */
    private java.lang.CharSequence actorId;
    /** Type of actor (USER, SYSTEM, SERVICE, etc.) */
    private java.lang.CharSequence actorType;
    /** UUID of the target entity being acted upon */
    private java.lang.CharSequence targetId;
    /** Type of target entity */
    private java.lang.CharSequence targetType;
    /** Code referencing audit_action_types table */
    private java.lang.CharSequence actionTypeCode;
    /** Code referencing audit_action_categories table */
    private java.lang.CharSequence actionCategoryCode;
    /** UUID if action performed on behalf of another user */
    private java.lang.CharSequence impersonatedUserId;
    /** JSON string of previous state */
    private java.lang.CharSequence previousData;
    /** JSON string of new state */
    private java.lang.CharSequence newData;
    /** Client IP address */
    private java.lang.CharSequence ipAddress;
    /** Client user agent string */
    private java.lang.CharSequence userAgent;
    /** Source device identifier */
    private java.lang.CharSequence sourceDevice;
    /** Timestamp when the audit log was created */
    private java.time.Instant createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mecare.avro.AuditLog.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.actorId)) {
        this.actorId = data().deepCopy(fields()[1].schema(), other.actorId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.actorType)) {
        this.actorType = data().deepCopy(fields()[2].schema(), other.actorType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.targetId)) {
        this.targetId = data().deepCopy(fields()[3].schema(), other.targetId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.targetType)) {
        this.targetType = data().deepCopy(fields()[4].schema(), other.targetType);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.actionTypeCode)) {
        this.actionTypeCode = data().deepCopy(fields()[5].schema(), other.actionTypeCode);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.actionCategoryCode)) {
        this.actionCategoryCode = data().deepCopy(fields()[6].schema(), other.actionCategoryCode);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.impersonatedUserId)) {
        this.impersonatedUserId = data().deepCopy(fields()[7].schema(), other.impersonatedUserId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.previousData)) {
        this.previousData = data().deepCopy(fields()[8].schema(), other.previousData);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.newData)) {
        this.newData = data().deepCopy(fields()[9].schema(), other.newData);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[10].schema(), other.ipAddress);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.userAgent)) {
        this.userAgent = data().deepCopy(fields()[11].schema(), other.userAgent);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.sourceDevice)) {
        this.sourceDevice = data().deepCopy(fields()[12].schema(), other.sourceDevice);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[13].schema(), other.createdAt);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
    }

    /**
     * Creates a Builder by copying an existing AuditLog instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mecare.avro.AuditLog other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.actorId)) {
        this.actorId = data().deepCopy(fields()[1].schema(), other.actorId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.actorType)) {
        this.actorType = data().deepCopy(fields()[2].schema(), other.actorType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.targetId)) {
        this.targetId = data().deepCopy(fields()[3].schema(), other.targetId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.targetType)) {
        this.targetType = data().deepCopy(fields()[4].schema(), other.targetType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.actionTypeCode)) {
        this.actionTypeCode = data().deepCopy(fields()[5].schema(), other.actionTypeCode);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.actionCategoryCode)) {
        this.actionCategoryCode = data().deepCopy(fields()[6].schema(), other.actionCategoryCode);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.impersonatedUserId)) {
        this.impersonatedUserId = data().deepCopy(fields()[7].schema(), other.impersonatedUserId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.previousData)) {
        this.previousData = data().deepCopy(fields()[8].schema(), other.previousData);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.newData)) {
        this.newData = data().deepCopy(fields()[9].schema(), other.newData);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[10].schema(), other.ipAddress);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.userAgent)) {
        this.userAgent = data().deepCopy(fields()[11].schema(), other.userAgent);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.sourceDevice)) {
        this.sourceDevice = data().deepCopy(fields()[12].schema(), other.sourceDevice);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[13].schema(), other.createdAt);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * UUID of the audit log entry
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * UUID of the audit log entry
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * UUID of the audit log entry
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * UUID of the audit log entry
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'actorId' field.
      * UUID of the user/system performing the action
      * @return The value.
      */
    public java.lang.CharSequence getActorId() {
      return actorId;
    }


    /**
      * Sets the value of the 'actorId' field.
      * UUID of the user/system performing the action
      * @param value The value of 'actorId'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setActorId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.actorId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'actorId' field has been set.
      * UUID of the user/system performing the action
      * @return True if the 'actorId' field has been set, false otherwise.
      */
    public boolean hasActorId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'actorId' field.
      * UUID of the user/system performing the action
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearActorId() {
      actorId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'actorType' field.
      * Type of actor (USER, SYSTEM, SERVICE, etc.)
      * @return The value.
      */
    public java.lang.CharSequence getActorType() {
      return actorType;
    }


    /**
      * Sets the value of the 'actorType' field.
      * Type of actor (USER, SYSTEM, SERVICE, etc.)
      * @param value The value of 'actorType'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setActorType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.actorType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'actorType' field has been set.
      * Type of actor (USER, SYSTEM, SERVICE, etc.)
      * @return True if the 'actorType' field has been set, false otherwise.
      */
    public boolean hasActorType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'actorType' field.
      * Type of actor (USER, SYSTEM, SERVICE, etc.)
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearActorType() {
      actorType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'targetId' field.
      * UUID of the target entity being acted upon
      * @return The value.
      */
    public java.lang.CharSequence getTargetId() {
      return targetId;
    }


    /**
      * Sets the value of the 'targetId' field.
      * UUID of the target entity being acted upon
      * @param value The value of 'targetId'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setTargetId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.targetId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'targetId' field has been set.
      * UUID of the target entity being acted upon
      * @return True if the 'targetId' field has been set, false otherwise.
      */
    public boolean hasTargetId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'targetId' field.
      * UUID of the target entity being acted upon
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearTargetId() {
      targetId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'targetType' field.
      * Type of target entity
      * @return The value.
      */
    public java.lang.CharSequence getTargetType() {
      return targetType;
    }


    /**
      * Sets the value of the 'targetType' field.
      * Type of target entity
      * @param value The value of 'targetType'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setTargetType(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.targetType = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'targetType' field has been set.
      * Type of target entity
      * @return True if the 'targetType' field has been set, false otherwise.
      */
    public boolean hasTargetType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'targetType' field.
      * Type of target entity
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearTargetType() {
      targetType = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'actionTypeCode' field.
      * Code referencing audit_action_types table
      * @return The value.
      */
    public java.lang.CharSequence getActionTypeCode() {
      return actionTypeCode;
    }


    /**
      * Sets the value of the 'actionTypeCode' field.
      * Code referencing audit_action_types table
      * @param value The value of 'actionTypeCode'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setActionTypeCode(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.actionTypeCode = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'actionTypeCode' field has been set.
      * Code referencing audit_action_types table
      * @return True if the 'actionTypeCode' field has been set, false otherwise.
      */
    public boolean hasActionTypeCode() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'actionTypeCode' field.
      * Code referencing audit_action_types table
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearActionTypeCode() {
      actionTypeCode = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'actionCategoryCode' field.
      * Code referencing audit_action_categories table
      * @return The value.
      */
    public java.lang.CharSequence getActionCategoryCode() {
      return actionCategoryCode;
    }


    /**
      * Sets the value of the 'actionCategoryCode' field.
      * Code referencing audit_action_categories table
      * @param value The value of 'actionCategoryCode'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setActionCategoryCode(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.actionCategoryCode = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'actionCategoryCode' field has been set.
      * Code referencing audit_action_categories table
      * @return True if the 'actionCategoryCode' field has been set, false otherwise.
      */
    public boolean hasActionCategoryCode() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'actionCategoryCode' field.
      * Code referencing audit_action_categories table
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearActionCategoryCode() {
      actionCategoryCode = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'impersonatedUserId' field.
      * UUID if action performed on behalf of another user
      * @return The value.
      */
    public java.lang.CharSequence getImpersonatedUserId() {
      return impersonatedUserId;
    }


    /**
      * Sets the value of the 'impersonatedUserId' field.
      * UUID if action performed on behalf of another user
      * @param value The value of 'impersonatedUserId'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setImpersonatedUserId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.impersonatedUserId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'impersonatedUserId' field has been set.
      * UUID if action performed on behalf of another user
      * @return True if the 'impersonatedUserId' field has been set, false otherwise.
      */
    public boolean hasImpersonatedUserId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'impersonatedUserId' field.
      * UUID if action performed on behalf of another user
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearImpersonatedUserId() {
      impersonatedUserId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'previousData' field.
      * JSON string of previous state
      * @return The value.
      */
    public java.lang.CharSequence getPreviousData() {
      return previousData;
    }


    /**
      * Sets the value of the 'previousData' field.
      * JSON string of previous state
      * @param value The value of 'previousData'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setPreviousData(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.previousData = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'previousData' field has been set.
      * JSON string of previous state
      * @return True if the 'previousData' field has been set, false otherwise.
      */
    public boolean hasPreviousData() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'previousData' field.
      * JSON string of previous state
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearPreviousData() {
      previousData = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'newData' field.
      * JSON string of new state
      * @return The value.
      */
    public java.lang.CharSequence getNewData() {
      return newData;
    }


    /**
      * Sets the value of the 'newData' field.
      * JSON string of new state
      * @param value The value of 'newData'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setNewData(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.newData = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'newData' field has been set.
      * JSON string of new state
      * @return True if the 'newData' field has been set, false otherwise.
      */
    public boolean hasNewData() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'newData' field.
      * JSON string of new state
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearNewData() {
      newData = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'ipAddress' field.
      * Client IP address
      * @return The value.
      */
    public java.lang.CharSequence getIpAddress() {
      return ipAddress;
    }


    /**
      * Sets the value of the 'ipAddress' field.
      * Client IP address
      * @param value The value of 'ipAddress'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setIpAddress(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.ipAddress = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'ipAddress' field has been set.
      * Client IP address
      * @return True if the 'ipAddress' field has been set, false otherwise.
      */
    public boolean hasIpAddress() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'ipAddress' field.
      * Client IP address
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearIpAddress() {
      ipAddress = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'userAgent' field.
      * Client user agent string
      * @return The value.
      */
    public java.lang.CharSequence getUserAgent() {
      return userAgent;
    }


    /**
      * Sets the value of the 'userAgent' field.
      * Client user agent string
      * @param value The value of 'userAgent'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setUserAgent(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.userAgent = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'userAgent' field has been set.
      * Client user agent string
      * @return True if the 'userAgent' field has been set, false otherwise.
      */
    public boolean hasUserAgent() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'userAgent' field.
      * Client user agent string
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearUserAgent() {
      userAgent = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'sourceDevice' field.
      * Source device identifier
      * @return The value.
      */
    public java.lang.CharSequence getSourceDevice() {
      return sourceDevice;
    }


    /**
      * Sets the value of the 'sourceDevice' field.
      * Source device identifier
      * @param value The value of 'sourceDevice'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setSourceDevice(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.sourceDevice = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'sourceDevice' field has been set.
      * Source device identifier
      * @return True if the 'sourceDevice' field has been set, false otherwise.
      */
    public boolean hasSourceDevice() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'sourceDevice' field.
      * Source device identifier
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearSourceDevice() {
      sourceDevice = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * Timestamp when the audit log was created
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * Timestamp when the audit log was created
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[13], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * Timestamp when the audit log was created
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * Timestamp when the audit log was created
      * @return This builder.
      */
    public com.mecare.avro.AuditLog.Builder clearCreatedAt() {
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AuditLog build() {
      try {
        AuditLog record = new AuditLog();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.actorId = fieldSetFlags()[1] ? this.actorId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.actorType = fieldSetFlags()[2] ? this.actorType : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.targetId = fieldSetFlags()[3] ? this.targetId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.targetType = fieldSetFlags()[4] ? this.targetType : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.actionTypeCode = fieldSetFlags()[5] ? this.actionTypeCode : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.actionCategoryCode = fieldSetFlags()[6] ? this.actionCategoryCode : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.impersonatedUserId = fieldSetFlags()[7] ? this.impersonatedUserId : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.previousData = fieldSetFlags()[8] ? this.previousData : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.newData = fieldSetFlags()[9] ? this.newData : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.ipAddress = fieldSetFlags()[10] ? this.ipAddress : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.userAgent = fieldSetFlags()[11] ? this.userAgent : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.sourceDevice = fieldSetFlags()[12] ? this.sourceDevice : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.createdAt = fieldSetFlags()[13] ? this.createdAt : (java.time.Instant) defaultValue(fields()[13]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AuditLog>
    WRITER$ = (org.apache.avro.io.DatumWriter<AuditLog>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AuditLog>
    READER$ = (org.apache.avro.io.DatumReader<AuditLog>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










